### ISSUE TITLE
Replace the use of `github.com/facebookgo/grace`

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/acadock-monitoring#31]
github.com/facebookarchive/grace is deprecated. It should be replaced. From what I remember, this is the same as github.com/cloudflare/tableflip used in git-repository-core, but this is yet to be confirmed.

**Comment by sc-zenokerr** [comment]
I have requested info from infosec regarding the use of the github.com/cloudflare/tableflip library.
Conv here: https://scalingo.slack.com/archives/C01U5K16FM2/p1718022497997279

**Comment by stplec** [comment]
created STORY-613

**Comment by leo-scalingo** [comment]
Just discussed with Zeno for the strategy for this issue.

The steps would be:

* Use tableflip in `go-utils/graceful` trying to keep the same API as currently (or only minor changes) to replace the use of `facebookgo/grace` which is unmaintained`
* Use `go-utils/graceful` in `acadock-monitoring` directly to drop `github.com/facebookgo/grace`
